#!/bin/bash
# 
# Created By Luo Yu(blodely, indie.luo@gmail.com)
# Wednesday, January 5, 2022
#

echo ""
echo ""
echo "----------------------------------"
echo ""
echo "Welcome to PodLibGenerator script!"
echo ""
echo "This script can and only generate local pod library."
echo ""
read -p "Creator name: " ip_creator
read -p "Creator email: " ip_email
read -p "Lib name: " ip_lib
timestamp=$(date)
echo ""
echo "----------------------------------"
echo "Generating LICENSE file:"

echo "Copyright (c) 2022 $ip_creator <$ip_email>

This is a private project. ALL RIGHTS RESERVED.
" > LICENSE
echo "done."
echo ""
echo "----------------------------------"
echo "Generating README file:"
echo "# $ip_lib

### Requirements

Cocoapods.

### Installation

$ip_lib is available through local [CocoaPods](https://cocoapods.org). To install
it, simply add the following line to your Podfile:

pod '$ip_lib', :path => '/path/to/local/module/'

### Author

$ip_creator, $ip_email

### License

$ip_lib is available under a private license. See the LICENSE file for more info.

" > README.md
echo "done."
echo ""
echo "----------------------------------"
echo "Generating Pod spec file:"
echo "#
# Created by $ip_creator
# $timestamp
#
Pod::Spec.new do |s|
  s.name             = '$ip_lib'
  s.version          = '0.1.0'
  s.summary          = '$ip_lib.'
  s.description      = <<-DESC
This is module $ip_lib.
  DESC
  s.homepage         = 'http://localhost'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { '$ip_creator' => '$ip_email' }
  s.source           = { :git => '', :tag => s.version.to_s }
  s.ios.deployment_target = '11.0'
  s.source_files = '$ip_lib/Classes/**/*'
  # s.resource_bundles = {
  #   '$ip_lib' => ['$ip_lib/Assets/*.png']
  # }
  s.frameworks = 'UIKit' #, 'MapKit'
  s.dependency 'LYCategory'
end
" > $ip_lib.podspec
echo "done."
echo ""
echo "----------------------------------"
echo "Creating folders..."
mkdir -p $ip_lib/Assets
mkdir -p $ip_lib/Classes
echo "" > $ip_lib/Assets/.gitkeep
echo "" > $ip_lib/Classes/.gitkeep
echo "//
// Generated by Rick Luo's script.
//" > $ip_lib/Classes/ReplaceMe.m
echo "done."
echo ""
echo "The End."
echo "----------------------------------"
